# Generated by Django 2.2.2 on 2023-06-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeployTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('uid', models.CharField(max_length=64, verbose_name='标识')),
                ('tag', models.CharField(max_length=32, verbose_name='版本号')),
                ('status', models.IntegerField(choices=[(1, '待发布'), (2, '发布中'), (3, '发布完成')], default=1, verbose_name='状态')),
                ('before_download_script', models.TextField(blank=True, null=True, verbose_name='下载前脚本')),
                ('after_download_script', models.TextField(blank=True, null=True, verbose_name='下载后脚本')),
                ('before_deploy_script', models.TextField(blank=True, null=True, verbose_name='发布前脚本')),
                ('after_deploy_script', models.TextField(blank=True, null=True, verbose_name='发布后脚本')),
            ],
        ),
        migrations.CreateModel(
            name='HookTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('content', models.TextField(verbose_name='脚本内容')),
                ('hook', models.IntegerField(choices=[(2, '下载前'), (4, '下载后'), (6, '发布前'), (8, '发布后')], verbose_name='钩子类型')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=32, verbose_name='节点文字')),
                ('status', models.CharField(choices=[('lightgray', '待发布'), ('green', '成功'), ('red', '失败')], default='lightgray', max_length=16, verbose_name='状态')),
                ('execute_records', models.TextField(blank=True, null=True, verbose_name='节点执行记录')),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='项目名')),
                ('repo', models.CharField(max_length=128, verbose_name='仓库地址')),
                ('env', models.CharField(choices=[('prod', '正式环境'), ('test', '测试环境')], default='test', max_length=16, verbose_name='环境')),
                ('path', models.CharField(max_length=128, verbose_name='线上项目地址')),
            ],
        ),
    ]
