# Generated by Django 2.2.2 on 2023-06-23 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('tools_execution', '0001_initial'),
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='pj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='programme',
            name='server',
            field=models.ManyToManyField(to='tools_execution.Accounts', verbose_name='关联服务器'),
        ),
        migrations.AddField(
            model_name='node',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deploy.Node', verbose_name='父节点'),
        ),
        migrations.AddField(
            model_name='node',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tools_execution.Accounts', verbose_name='服务器'),
        ),
        migrations.AddField(
            model_name='node',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy.DeployTask', verbose_name='发布任务单'),
        ),
        migrations.AddField(
            model_name='hooktemplate',
            name='pj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='deploytask',
            name='pj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='deploytask',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy.Programme', verbose_name='项目环境'),
        ),
    ]
