# Generated by Django 2.2.2 on 2023-06-23 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('tools_execution', '0001_initial'),
        ('batchTasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklogdetail',
            name='host_to_remote_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools_execution.Accounts', verbose_name='远程服务器'),
        ),
        migrations.AddField(
            model_name='tasklogdetail',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='batchTasks.Task'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='项目'),
        ),
    ]
