# Generated by Django 2.2.2 on 2023-06-23 12:09

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='分组名称')),
            ],
        ),
        migrations.CreateModel(
            name='FileRespository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='文件名称')),
                ('suffix', models.CharField(max_length=16, verbose_name='文件后缀')),
                ('file', models.FileField(upload_to='upload/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileRespositoryShareThings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='邀请码')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='FileSendRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='单号')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('records', models.TextField(blank=True, null=True, verbose_name='分发结果')),
            ],
        ),
        migrations.CreateModel(
            name='Scripts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_created=True, auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=64, verbose_name='工具名称')),
                ('content', ckeditor.fields.RichTextField(verbose_name='脚本代码')),
                ('showImage', models.ImageField(choices=[('/static/img/python.png', '/static/img/python.png'), ('/static/img/shell.png', '/static/img/shell.png'), ('/static/img/go.jpg', '/static/img/go.jpg'), ('/static/img/java.png', '/static/img/java.png'), ('/static/img/js.jpg', '/static/img/js.jpg')], default='/static/img/python.png', upload_to='', verbose_name='logo')),
                ('desc', models.CharField(default='', max_length=200, verbose_name='工具描述')),
                ('suffix', models.CharField(max_length=16, verbose_name='工具后缀')),
            ],
            options={
                'verbose_name': '脚本信息',
                'verbose_name_plural': '脚本信息',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ShareThings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='邀请码')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='ToolsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='分组名称')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.Project', verbose_name='项目')),
            ],
        ),
    ]
