# Generated by Django 2.2.2 on 2023-06-23 12:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('label', models.CharField(max_length=32, verbose_name='标签')),
                ('codeName', models.CharField(max_length=32, verbose_name='代码段名称')),
                ('content', ckeditor.fields.RichTextField(verbose_name='代码段内容')),
                ('showImage', models.ImageField(choices=[('/static/img/python.png', '/static/img/python.png'), ('/static/img/shell.png', '/static/img/shell.png'), ('/static/img/go.jpg', '/static/img/go.jpg'), ('/static/img/java.png', '/static/img/java.png'), ('/static/img/js.jpg', '/static/img/js.jpg')], default='/static/img/python.png', upload_to='', verbose_name='logo')),
                ('suffix', models.CharField(max_length=16, verbose_name='工具后缀')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('ip', models.GenericIPAddressField(default='0.0.0.0', unique=True)),
                ('external_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='公网地址')),
                ('mac', models.CharField(default='', max_length=32)),
                ('os', models.CharField(default='', max_length=64)),
                ('arch', models.CharField(default='', max_length=16)),
                ('mem', models.BigIntegerField(default=0)),
                ('cpu', models.IntegerField(default=0)),
                ('disk', models.CharField(default='{}', max_length=5120)),
                ('sn', models.CharField(default='', max_length=128)),
                ('user', models.CharField(default='', max_length=128)),
                ('remark', models.IntegerField(default=1)),
                ('purchase_time', models.DateTimeField()),
                ('over_insurance_time', models.DateTimeField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='module名称')),
                ('redirect_url', models.CharField(max_length=128, verbose_name='要跳转的地址')),
                ('desc', models.CharField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('logoUrl', models.CharField(blank=True, max_length=256, null=True, verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(default='0.0.0.0')),
                ('cpu', models.FloatField(default=0)),
                ('mem', models.FloatField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(verbose_name='pid')),
                ('ppid', models.IntegerField(verbose_name='ppid')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('exe', models.CharField(max_length=256, verbose_name='exe')),
                ('cpu_percent', models.FloatField(verbose_name='cpu_percent')),
                ('nice_priority', models.IntegerField(verbose_name='优先级')),
                ('username', models.CharField(max_length=32, verbose_name='进程用户')),
                ('status', models.CharField(max_length=32, verbose_name='状态')),
                ('mem', models.FloatField(verbose_name='内存')),
                ('cwd', models.CharField(max_length=128, verbose_name='路径')),
                ('last_time', models.DateTimeField(verbose_name='最新上报时间')),
                ('host', models.ManyToManyField(blank=True, null=True, to='cmdb.Host', verbose_name='关联服务器')),
            ],
        ),
    ]
