# Generated by Django 2.2.2 on 2023-06-23 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmdb', '0001_initial'),
        ('project', '0001_initial'),
        ('tools_execution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='host',
            name='server_to_server',
            field=models.ManyToManyField(blank=True, null=True, to='tools_execution.Accounts'),
        ),
    ]
