# Generated by Django 2.2.2 on 2023-06-23 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolsLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=32, verbose_name='执行目标')),
                ('env', models.CharField(max_length=128, verbose_name='执行环境')),
                ('creator', models.CharField(max_length=10, verbose_name='执行用户')),
                ('script', models.CharField(max_length=32, verbose_name='关联工具')),
                ('script_id', models.IntegerField(verbose_name='关联工具ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('server', models.CharField(max_length=20, verbose_name='执行服务器')),
                ('content', models.CharField(blank=True, max_length=256, null=True, verbose_name='拓展')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='关联项目')),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.GenericIPAddressField(verbose_name='服务器地址')),
                ('username', models.CharField(max_length=32, verbose_name='账户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('port', models.IntegerField(default=22, verbose_name='端口')),
                ('desc', models.CharField(max_length=256, verbose_name='描述信息')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='关联项目')),
            ],
        ),
    ]
