# Generated by Django 2.2.2 on 2023-06-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_execution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolslogs',
            name='project',
        ),
        migrations.AddField(
            model_name='toolslogs',
            name='project_name',
            field=models.CharField(default=1, max_length=64, verbose_name='关联项目'),
            preserve_default=False,
        ),
    ]
