# Generated by Django 2.2.2 on 2023-06-23 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('django_apscheduler', '0008_remove_djangojobexecution_started'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=1024, verbose_name='任务id')),
                ('cmd', models.CharField(max_length=1024, verbose_name='执行命令')),
                ('operate_condition', models.CharField(max_length=64, verbose_name='运算条件')),
                ('alarm_threshold', models.CharField(max_length=1024, verbose_name='告警阈值')),
                ('alarm_way', models.CharField(max_length=64, verbose_name='告警方式')),
            ],
        ),
        migrations.CreateModel(
            name='FastTasksEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.CharField(max_length=128, verbose_name='邮件配置参数')),
            ],
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=1024, verbose_name='任务id')),
                ('status', models.IntegerField(verbose_name='状态')),
                ('exe_time', models.DateTimeField(verbose_name='执行时间')),
                ('cmd', models.CharField(max_length=1024, verbose_name='执行命令')),
                ('stdout', models.TextField(verbose_name='执行输出')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='关联项目')),
            ],
        ),
        migrations.CreateModel(
            name='StoreInfos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.CharField(max_length=1024, verbose_name='执行命令')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='关联项目')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='djangojob', to='django_apscheduler.DjangoJob', verbose_name='task_id')),
            ],
        ),
    ]
