# Generated by Django 2.2.2 on 2023-06-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_scheduler', '0002_auto_20230623_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklog',
            name='project',
        ),
        migrations.AddField(
            model_name='tasklog',
            name='project_name',
            field=models.CharField(default=1, max_length=64, verbose_name='关联项目'),
            preserve_default=False,
        ),
    ]
