# Generated by Django 2.2.2 on 2023-06-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='站点名称')),
                ('module', models.CharField(max_length=32, verbose_name='所属模块')),
                ('category', models.CharField(max_length=32, verbose_name='分类')),
                ('link', models.CharField(max_length=64, verbose_name='链接')),
                ('visible', models.BooleanField(default=True, max_length=32, verbose_name='是否可见')),
                ('logo', models.CharField(max_length=32, verbose_name='站点logo')),
            ],
        ),
    ]
